image: maven:3.6.0-jdk-8

stages:
  - test

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -DJAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Dhttps.proxyHost=proxy.hcm.fpt.vn -Dhttps.proxyPort=80 -Dhttp.proxyHost=proxy.hcm.fpt.vn -Dhttp.proxyPort=80 -Dhttp.nonProxyHosts=seleniumhub.fpt.net|upload-static.fpt.net|systemmailapi.fpt.vn -DsuiteXmlFile=testng_retry.xml -DgridEnabled=true -DenableEmailReport=true -DenableUploadFile=true -DtoEmailReport=HungNDT2@FPT.COM.VN;DienLT2@FPT.COM.VN;minhlh5@fpt.com.vn;TuanNN16@fpt.com.vn;NhuVTQ5@FPT.COM.VN"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

test-consumer:
  stage: test
  tags:
    - selenium-docker
  script:
    - echo '172.20.23.90 upload-static.fpt.net' >> /etc/hosts
    #- mvn $MAVEN_CLI_OPTS verify
  artifacts:
    when: always
    paths:
      - logs/*.log
    expire_in: 1 week